### PR TITLE
Documented Github Pages deployment set up.

### PR DESCRIPTION
**Pull request by dglazkov**
This is based on experience with a couple of projects.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/DevProgress/onboarding/pull/6" target="_blank">ReviewNinja

**Comment by samuelcole** [comment]
👍

**Comment by samuelcole** [comment]
it's unfortunate it's `/docs`, but it is what it is.

it would also be cool to standardize a deploy script? that built and committed the production bundle, but this is a good start

**Comment by dglazkov** [comment]
Good idea on the deploy script. Filed #7.

**Pull request merged**
